// Writes REGISTRY.md: a human- and agent-readable index of the whole catalog, meant as context
// when planning work (what exists, what each item installs, where the gaps are).
//
//   pnpm exec tsx ./scripts/registry/gen-registry-md.mts
import { writeFile } from "node:fs/promises"

const { registry } = await import("@/registry/index")
const { registryAddress, siteConfig } = await import("@/config/site")
const { PROJECTS } = await import("@/config/projects")
const { KIND_LABEL, REGISTRY_KINDS, kindOf } =
  await import("@/lib/registry-kinds")
const { prepareItems } = await import("@/lib/registry-source")

const prepared = await prepareItems()

const lines: string[] = []
const p = (line = "") => lines.push(line)

p("# Registry Catalog")
p()
p(
  "<!-- Autogenerated by scripts/registry/gen-registry-md.mts. Run `pnpm registry:build`; do not edit. -->"
)
p()
p(
  `Every item published by \`${registry.name}\`, grouped by kind. ${registry.items.length} items in total.`
)
p()

for (const kind of REGISTRY_KINDS) {
  const ofKind = prepared.filter((entry) => kindOf(entry.item) === kind)
  if (!ofKind.length) continue

  p(`## ${KIND_LABEL[kind]}s (${ofKind.length})`)
  p()
  p("| Item | Project | Title | Installs to | Description |")
  p("| --- | --- | --- | --- | --- |")

  for (const { item, project, files } of ofKind) {
    const targets = files.map((file) => `\`${file.target}\``).join("<br>")
    p(
      `| \`${registryAddress(item.name)}\` | ${PROJECTS[project]?.name ?? project} | ${item.title ?? ""} | ${targets} | ${item.description ?? ""} |`
    )
  }
  p()
}

p("## Installing")
p()
p("```sh")
p(`pnpm dlx shadcn@latest add ${registryAddress("<item-name>")}`)
p("```")
p()
p(
  `Register the namespace once in \`components.json\`: \`"@${siteConfig.SLUG}": "${siteConfig.URL}/r/{name}.json"\`.`
)
p()

await writeFile("REGISTRY.md", lines.join("\n"))
console.log(`REGISTRY.md: ${registry.items.length} items indexed`)
