// Regenerates the derived registry artifacts. Run via `pnpm registry:build`.
//
//   registry/registry-items.ts  (authored)
//     -> config/{components,blocks,templates}.ts   site data: metadata + embedded source
//     -> registry.json                             the source registry `shadcn build` reads
//
// Imports are dynamic so tsx resolves the `@/` alias before this module's body runs.
import fs from "node:fs/promises"
import path from "node:path"
import { rimraf } from "rimraf"

const { registry } = await import("@/registry/index")
const { loadCode } = await import("@/lib/code")
const { assertRegistryInvariants } = await import("@/lib/registry-invariants")
const { absolutizeAssets } = await import("@/lib/registry-assets")
const { baseUiDocs, withBaseUiRuntime } = await import("@/lib/registry-runtime")
const { cssVarsForTokens, detectStateTokens } =
  await import("@/registry/tokens")
const { KIND_PLURAL, REGISTRY_KINDS } = await import("@/lib/registry-kinds")
const { prettifySlug } = await import("@/lib/utils")
const { rewriteItemImports } = await import("@/lib/registry-imports")
const { getLang, prepareItems, previewPath } =
  await import("@/lib/registry-source")
type PreparedItem = Awaited<ReturnType<typeof prepareItems>>[number]

// The site's copy of the catalog: the same source the published artifact carries, so the two cannot disagree.
async function buildSiteData(prepared: PreparedItem[]) {
  const entries = await Promise.all(
    prepared.map(async ({ item, kind, project, files }) => {
      // Shown in the code view so a consumer can see how to mount the item, never published.
      // Its imports get the same rewrite as the item's own files, or it would show a relative
      // path that does not resolve to where `shadcn add` actually writes the block.
      const previewFile = previewPath(kind, item.name, project)
      const preview = {
        type: "page",
        name: "page.tsx",
        code: absolutizeAssets(
          rewriteItemImports(await loadCode(previewFile), previewFile, files)
        ),
        lang: "tsx",
        target: null,
      }

      const itemFiles = files.map((file) => ({
        type: file.type.replace("registry:", ""),
        name: file.path.split("/").pop() ?? "",
        code: file.content,
        lang: getLang(file.path),
        target: file.target,
      }))

      return {
        kind,
        name: item.name,
        project,
        title: item.title ?? prettifySlug(item.name),
        height: (item.meta?.height as string) || "100vh",
        description: item.description ?? "",
        registryDependencies: item.registryDependencies ?? [],
        dependencies: item.dependencies ?? [],
        // A template ships its own page, so the preview entry would just be a duplicate.
        files: kind === "template" ? itemFiles : [preview, ...itemFiles],
      }
    })
  )

  // loadCode returns a marker for a missing file so the UI degrades; generation refuses to ship one.
  assertRegistryInvariants(
    entries.map((entry) => ({
      name: entry.name,
      files: entry.files.map((file) => ({
        path: file.name,
        content: file.code,
      })),
    })),
    { requireContent: true }
  )

  for (const kind of REGISTRY_KINDS) {
    const ofKind = entries.filter((entry) => entry.kind === kind)
    const plural = KIND_PLURAL[kind]
    const output = `// Autogenerated by lib/build-registry.mts. Run \`pnpm registry:build\`; do not edit.
// "server-only" keeps the embedded source out of every client bundle.
import "server-only"

import type { RegistryEntry } from "@/lib/types"

export const ${plural}: RegistryEntry[] = ${JSON.stringify(ofKind, null, 2)}
`
    await fs.writeFile(path.join(process.cwd(), `config/${plural}.ts`), output)
    console.log(`config/${plural}.ts: ${ofKind.length} ${plural} embedded`)
  }
}

// The source registry `shadcn build` turns into public/r/*.json, with every derived field applied.
async function buildRegistryJsonFile(prepared: PreparedItem[]) {
  const items = prepared.map(({ item, files }) => {
    const source = files.map((file) => file.content).join("\n")
    const docs = baseUiDocs(source)
    const cssVars = cssVarsForTokens(detectStateTokens(source))

    return {
      ...item,
      ...(docs ? { docs } : {}),
      ...(cssVars ? { cssVars } : {}),
      dependencies: withBaseUiRuntime(
        item.dependencies,
        item.registryDependencies
      ),
      // Content is dropped here: `shadcn build` inlines it from disk, and
      // scripts/registry/finalize-artifacts.mts then applies the rewrites.
      files: files.map(({ content: _content, ...file }) => file),
    }
  })

  assertRegistryInvariants(items)

  const outputPath = path.join(process.cwd(), "registry.json")
  await rimraf(outputPath)
  await fs.writeFile(
    outputPath,
    `${JSON.stringify(
      {
        $schema: "https://ui.shadcn.com/schema/registry.json",
        ...registry,
        items,
      },
      null,
      2
    )}\n`
  )
  console.log(`registry.json: ${items.length} items written`)
}

async function main() {
  // Renaming an item would otherwise leave its old JSON behind in public/r,
  // and `shadcn build` only ever writes, never prunes.
  await rimraf(path.join(process.cwd(), "public/r"))

  const prepared = await prepareItems()
  await buildSiteData(prepared)
  await buildRegistryJsonFile(prepared)
}

main().catch((error: unknown) => {
  console.error("Registry build failed:")
  console.error(error)
  process.exit(1)
})
