// Autogenerated by lib/build-registry.mts. Run `pnpm registry:build`; do not edit.
// "server-only" keeps the embedded source out of every client bundle.
import "server-only"

import type { RegistryEntry } from "@/lib/types"

export const components: RegistryEntry[] = [
  {
    "kind": "component",
    "name": "openlmis-status-pill",
    "project": "openlmis",
    "title": "Requisition Status Pill",
    "height": "84px",
    "description": "Badge that renders an OpenLMIS requisition status with the colour and label matched to its stage, from initiated through to released.",
    "registryDependencies": [
      "badge"
    ],
    "dependencies": [],
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "code": "import { REQUISITION_STATUSES, StatusPill } from \"@/components/openlmis/status-pill\"\n\nexport default function Page() {\n  return (\n    <div className=\"flex w-full flex-wrap items-center justify-center gap-2 p-8\">\n      {REQUISITION_STATUSES.map((status) => (\n        <StatusPill key={status} status={status} />\n      ))}\n    </div>\n  )\n}",
        "lang": "tsx",
        "target": null
      },
      {
        "type": "component",
        "name": "status-pill.tsx",
        "code": "import { Badge } from \"@/components/ui/badge\"\n\n// The OpenLMIS requisition lifecycle, in the order a requisition moves through it.\nexport const REQUISITION_STATUSES = [\n  \"initiated\",\n  \"submitted\",\n  \"authorized\",\n  \"in-approval\",\n  \"approved\",\n  \"released\",\n  \"rejected\",\n] as const\n\nexport type RequisitionStatus = (typeof REQUISITION_STATUSES)[number]\n\nconst STATUS_VARIANT: Record<\n  RequisitionStatus,\n  React.ComponentProps<typeof Badge>[\"variant\"]\n> = {\n  initiated: \"outline\",\n  submitted: \"secondary\",\n  authorized: \"secondary\",\n  \"in-approval\": \"secondary\",\n  approved: \"default\",\n  released: \"default\",\n  rejected: \"destructive\",\n}\n\nconst STATUS_LABEL: Record<RequisitionStatus, string> = {\n  initiated: \"Initiated\",\n  submitted: \"Submitted\",\n  authorized: \"Authorized\",\n  \"in-approval\": \"In approval\",\n  approved: \"Approved\",\n  released: \"Released\",\n  rejected: \"Rejected\",\n}\n\nexport function StatusPill({\n  status,\n  ...props\n}: Omit<React.ComponentProps<typeof Badge>, \"variant\" | \"children\"> & {\n  status: RequisitionStatus\n}) {\n  return (\n    <Badge variant={STATUS_VARIANT[status]} {...props}>\n      {STATUS_LABEL[status]}\n    </Badge>\n  )\n}",
        "lang": "tsx",
        "target": "components/openlmis/status-pill.tsx"
      }
    ]
  }
]
