// Autogenerated by lib/build-registry.mts. Run `pnpm registry:build`; do not edit.
// "server-only" keeps the embedded source out of every client bundle.
import "server-only"

import type { RegistryEntry } from "@/lib/types"

export const templates: RegistryEntry[] = []
